

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Conclusion of Data Report

Through our _**HousingApp**_, we closely analyzed the housing and rental trends in Seattle to better understand the effect of gentrification in Seattle. We compared these trends with National housing and rental rates, housing and rental rates in other U.S. cities , and housing and rental rates of other cities in Washington State. We allowed users to interact with the data presented in various line plots by choosing the data that they wanted to see in order to better understand the various differences and trends in housing and rental rates. We also presented an interactive map visualization of the Seattle area that allows users to explore specific details about housing and rental rates in Seattle. We answered specific critical analysis questions for each part of our analysis while using our visualizations to enhance the overall user experience, and create an interactive and cohesive report for users to learn more about trends involving gentrification. Our interactive application also helps the users better understand the relevance of the data that they are interacting with, and why gentrification is such a significant topic in today's world. 

**QUESTIONS**

1) *An increase in housing and rental prices is one of the signs that a city is experiencing gentrification. If Seattle was experiencing gentrification, it would be expected that there would be a greater increase in Seattle housing and rental prices compared to the national averages in housing and rental prices. Knowing this, is it true that Seattle experiences a more rapid increase in housing and rental prices compared to national yearly averages?*

Yes, the visualization shows that the increase in both housing and rental prices in Seattle (increase by 63.71%, 30.07%, respectively) is much greater than the average increase in housing and rental prices on the national level (increase by 35.13%, 13.29%). This may imply that Seattle is likely experiencing more gentrification than the rest of the nation. This may cause lower-income families(and some middle class) to be unable to afford rental on houses/apartments, or find permanent residence in a house.

2) *What are the trends of housing and rental prices in Seattle by year?*

Both housing and rental prices in Seattle were on an increasing trend, but increasing at diffent rates. More specifically, the housing prices in Seattle increased way faster (63.71%) than the rental prices in Seattle (35.13%). This may imply that not only low-income people will struggle more to afford housing, and more people will have a difficult time adjusting to the sharp increase in housing and rental prices.The greater increase in housing prices may also be because the flourishing job industry means that more people are looking for long term housing for their families, and the increased demand causes a greater increase in housing prices as a result.

3) *Due to gentrification, is it true that the Seattle area experiences a faster increase in housing and rental prices compared to the rest of Washington State?*

The Seattle area experienced a much greater and faster increase in housing and rental prices compared to the rest of Washington State. Washington State outside of Seattle experienced a relatively fast growth in house and rental prices  (increased by 42.81%, 22.4% respectively). However, housing and rental prices in Seattle experienced an even greater increase over the same time(increase by 63.71%, 30.07% respectively). This could imply that the increase in prices is not solely because of a positive trend in Washington state in the price of house and rental, but it would be more as a result of the growing economy and flourishing industry in Seattle.

4) *As a result of gentrification, is it true that the Seattle area experiences a faster increase in housing and rental prices compared with other cities, such as San Francisco, where there may also be effects of gentrification?*

Seattle is one of the fastest growing cities out of all the cities in our data. There was only one city, San Francisco, that had a greater rate of change in price of housing and rental (rent: 34.4% for SF vs 30.07% for Seattle; house: 62.42% for SF 63.71% vs for Seattle). This implies that the great increase in housing and rental prices in Seattle is not solely because of the positive economic trend in the United States, especially in mid to big cities. 